# Demo CI workflow with TcUnit-Runner
name: TcUnit-Runner  
 
trigger:
  - main
pr:
  - main  
 
pool: 'Default'    # self-hosted agent  
 
steps:

- checkout: self
  displayName: 'Checkout repository'

- task: CmdLine@2
  displayName: 'Run unit tests with TcUnit-Runner'
  inputs:
    script: '"C:\Program Files (x86)\TcUnit-Runner\LaunchTcUnit.bat" -u 5 -t TestTask'
    failOnStderr: true
     
- task: PublishTestResults@2
  displayName: Publish TcUnit results
  condition: or(succeeded(),failed())     
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TcUnit_xUnit_results.xml'