# Demo CI workflow with C# tests
name: MSTest-Runner 
 
trigger:
  - MSTest
pr:
  - MSTest
 
pool: 'Default'    # self-hosted agent  
 
steps:

- checkout: self
  displayName: 'Checkout repository'

- task: CmdLine@2
  displayName: 'Run unit tests with TcUnit-Runner'
  inputs:
    script: '"C:\Program Files (x86)\TcUnit-Runner\LaunchTcUnit.bat" -u 5'
    failOnStderr: true

- task: PowerShell@2
  displayName: 'Build, activate and run script'
  inputs:
    script: './tc_build_run.ps1'
    failOnStderr: true

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: './TCxUnitTester/*.csproj'