# Demo CI workflow with C# tests
name: MSTest-Runner 
 
trigger:
  - MSTest
pr:
  - MSTest
 
pool: 'Default'    # self-hosted agent  
 
steps:

- checkout: self
  displayName: 'Checkout repository'

- task: PowerShell@2
  displayName: 'Build, activate and run script'
  inputs:
    filePath: './tc_build_run.ps1'
    failOnStderr: true

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: './TCxUnitTester/TCxUnitTester.csproj'