<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_TEST" Id="{d8ef3780-da63-4f67-b013-b5f69f0f0425}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TEST
VAR
	fbCheckPartTest		: FB_TEST_CheckPartGood(sName:= 'CheckPartGood');
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PRG_TEST">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>